<?xml version="1.0"?>
<package format="3">
  <name>mpc_solver</name>
  <version>0.1.0</version>
  <description>acados solver adapters for the HMPC controllers</description>

  <maintainer email="d.benders@tudelft.nl">Dennis Benders</maintainer>
  <author>Dennis Benders</author>
  <author>Thijs Niesten</author>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen</depend>
  <depend>mpc_base</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
