<?xml version="1.0"?>
<package format="3">
  <name>mpc_tools</name>
  <version>0.0.1</version>
  <description>The mpc_tools package</description>

  <maintainer email="d.benders@tudelft.nl">Dennis Benders</maintainer>
  <author>Dennis Benders</author>
  <author>Thijs Niesten</author>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>boost</depend>
  <depend>eigen</depend>
  <depend>geometry_msgs</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>visualization_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>